project:
  type: book
  output-dir: docs

book:
  title: "데이터 과학 교육을 위한 10가지 간단한 규칙"
  author: "Tiffany A. Timbers, Mine Çetinkaya-Rundel"
  date: "1/24/2026"
  chapters:
    - index.qmd
    
bibliography: references.bib

format:
  html:
    theme:
      - default
      - brand

execute:
  freeze: auto